### ISSUE TITLE
The operation has timed out

### ISSUE THREAD

**Issue by vovikdrg** [urielha/log4stash-old#11]
Hi i am using latest version of log4stash and i am getting this error...

2015-11-21 02:21:06,114 [37] FATAL CommunicationErrorWriteToFile - Program Unhandled exception
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at log4net.ElasticSearch.WebElasticClient.FinishGetResponse(IAsyncResult result) in d:\uriel\Programing\C#\log4stash\src\log4net.ElasticSearch\ElasticClient.cs:line 110
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.HttpWebRequest.Abort(Exception exception, Int32 abortState)
   at System.Net.HttpWebRequest.AbortWrapper(Object context)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by urielha** [comment]
Hi,
From first glance, the problem seems to be related to your elastic server or mistake in the configuration.
What is your configuration? 
Did you try to switch the async off (`<IndexAsync>False</IndexAsync>`) and see whats happened?

Best regards

**Comment by vovikdrg** [comment]
I have changed to this i see that you have bulk feature. So will monitor, other question is this possible to set multiple servers`?

```
<appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4stash">
      <Server>SERVER</Server>
      <Port>9200</Port>
      <IndexName>log4net-%{+yyyy.MM}</IndexName>
      <Bulksize>2000</Bulksize>
      <BulkIdleTimeout>10000</BulkIdleTimeout>
      <IndexAsync>False</IndexAsync>
      <ElasticFilters>
        <Add>
          <Key>@type</Key>
          <Value>TYPE</Value>
        </Add>
      </ElasticFilters>
      <threshold value="ALL" />
      <filter type="log4net.Filter.LoggerMatchFilter">
        <loggerToMatch value="*StructureMapTaskFactory" />
      </filter>
      <filter type="log4net.Filter.DenyAllFilter" />
    </appender>
```

**Comment by vovikdrg** [comment]
Well for few days service still working so you can close this task
